### ISSUE TITLE
 Compilation error on file web/router.ex ==

### ISSUE THREAD

**Issue by tierralibre** [britton-jb/sentinel#29]
When applying the routes as per the README:

```elixir
defmodule` MyApp.Router do
  use MyApp.Web, :router
  require Sentinel
 

 pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
   
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :ueberauth
    Sentinel.mount_ueberauth
  end

  scope "/" do
    pipe_through :browser
    Sentinel.mount_html
  end

  scope "/api", as: :api do
    pipe_through :api
    Sentinel.mount_api
  end

end
```
```
== Compilation error on file web/router.ex ==
** (CompileError) web/router.ex:1: undefined function ueberauth/2
    (stdlib) lists.erl:1338: :lists.foreach/2
    (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

As per the instructions ueberauth is set as an application.

When commenting out: 
```elixir
#scope "/" do
  #  pipe_through :ueberauth
  #  Sentinel.mount_ueberauth
  #end
```
The compiling error goes away.

Testing with: 
```elixir
defmodule MyApp.Router do
  use MyApp.Web, :router
  require Sentinel
 

 pipeline :browser do
    plug Ueberauth
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
   
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  #scope "/" do
  #  pipe_through :ueberauth
  #  Sentinel.mount_ueberauth
  #end

  scope "/" do
    pipe_through :browser
    Sentinel.mount_html
    Sentinel.mount_ueberauth
  end

  scope "/api", as: :api do
    pipe_through :api
    Sentinel.mount_api
  end

end
```

**Comment by britton-jb** [comment]
I must have missed something in updating the README to configure that properly. I'll get that sorted. Thanks.

**Comment by britton-jb** [comment]
After investigation this was just something I had missed in the README. I'll be updating it with the following information shortly, but `pipethrough :ueberauth` is causing the issue because that isn't something that I explicitly defined in Sentinel, it was a pipeline I used in the test module, defined as:

```elixir
  pipeline :ueberauth do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_flash
    plug :put_secure_browser_headers
  end
```

If you want to use Sentinel using the browser, or the API exclusively you can pipe it through a browser or API pipeline as defined in your app.

I'll update this issue again, and close it, after I update the README.

**Comment by britton-jb** [comment]
Updated this to clarify in the README.
