### ISSUE TITLE
Error compiling - no function clause matching in Keyword.merge/2

### ISSUE THREAD

**Issue by TigerWolf** [britton-jb/sentinel#34]
Im getting this error when I tried upgrading Sentinel from 1 to 2.

```
== Compilation error on file lib/sentinel/web/controllers/auth_controller.ex ==
** (FunctionClauseError) no function clause matching in Keyword.merge/2
    (elixir) lib/keyword.ex:579: Keyword.merge(nil, [])
    lib/ueberauth.ex:175: Ueberauth.init/1
    (plug) lib/plug/builder.ex:193: Plug.Builder.init_module_plug/3
    (plug) lib/plug/builder.ex:181: anonymous fn/4 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:181: Plug.Builder.compile/3
    (phoenix) expanding macro: Phoenix.Controller.Pipeline.__before_compile__/1
    lib/sentinel/web/controllers/auth_controller.ex:1: Sentinel.Controllers.AuthController (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

I tried to narrow down where the error was being caused and had trouble making any in-roads.

**Comment by TigerWolf** [comment]
Looks like I was missing my `config :ueberauth` - I had added this and it works now.
