### ISSUE TITLE
Error when using it inside an umbrella

### ISSUE THREAD

**Issue by mrkaspa** [britton-jb/sentinel#35]
Crashes looking for the deps folder when I do mix sentinel.install

**Comment by britton-jb** [comment]
Looks like I'll have to setup a proper mix task for this. Thank you for sending this over.

**Comment by cdesch** [comment]
@mrkaspa  is this the error you're getting?

```
 (FunctionClauseError) no function clause matching in Keyword.merge/2
    (elixir) lib/keyword.ex:579: Keyword.merge(nil, [])
    lib/ueberauth.ex:175: Ueberauth.init/1
    (plug) lib/plug/builder.ex:193: Plug.Builder.init_module_plug/3
    (plug) lib/plug/builder.ex:181: anonymous fn/4 in Plug.Builder.compile/3
    (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
    (plug) lib/plug/builder.ex:181: Plug.Builder.compile/3
    (phoenix) expanding macro: Phoenix.Controller.Pipeline.__before_compile__/1
    lib/sentinel/web/controllers/auth_controller.ex:1: Sentinel.Controllers.AuthController (module)
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1

could not compile dependency :sentinel, "mix compile" failed. You can recompile this dependency with "mix deps.compile sentinel", update it with "mix deps.update sentinel" or clean it with "mix deps.clean sentinel"
cjs-MBP15:my_rewards_web cj$ 

```
